// The sweep's child process: `bun src/sweep/child.ts <job.json>`, spawned by run.ts in a temp directory with only PATH, HOME
// and TMPDIR in its environment. It loads no TypeScript library. It writes JSON lines to stdout and keeps only per-site
// counters and one first input per site and level; inputs are regenerated by index.
//   run:    every entry of the job over the lattice, through the instrumented copy
//   verify: each listed input through the instrumented copy, then the uninstrumented copy with console.assert recording
//           the failing lines of the analyzed file
// The child exits right after its `done` line, so a timer that project code started at module level, e.g. `setInterval`,
// doesn't keep it running until the parent's heartbeat limit.
// Structure from mutation-instrument-spike at bccf0dd: worker.ts runBaseline and runVerify, child-calls.ts causeOf and
// callEntry. The console replacements, R1 recorder, load step and heartbeat cadence are new.
import {readFileSync} from 'node:fs'
import {maxMagnitude, type Value} from './domain.ts'
import {encodeJson} from './encode.ts'
import {compileLattice, DIGEST_START, digestValue, inputAt, type Lattice} from './lattice.ts'
import {writeAll} from './pipe.ts'
import {BUDGET, createRecorder, DISCARD, resetRecorder} from './recorder.ts'
import {CAUSES, DISCARD_CAUSES, type CauseClass, type ChildLine, type DiscardCause, type FirstInput, type SiteCounts, type SweepEntry, type SweepJob} from './types.ts'

// Protocol writes go through references taken before any project code loads, so a module that replaces
// process.stdout.write or JSON.stringify can't break the protocol line that reports a crash. writeAll writes the whole line
// before returning, waiting while the pipe is full.
const writeLine = writeAll
const stringify = JSON.stringify
function emit(line: ChildLine) {
  writeLine(1, `${encodeJson(line)}\n`)
}

const job = JSON.parse(readFileSync(process.argv[2] ?? '', 'utf8')) as SweepJob
const childPath = import.meta.path

// Project code's console output is dropped; its failing console.asserts are recorded. The analyzed file's asserts are
// rewritten to __fr calls in the instrumented copy, so in run mode and during an instrumented call any console.assert that
// fails comes from an imported module (R1). During an uninstrumented call, the innermost frame outside this file decides.
const noop = () => {}
// Project writes to stdout and stderr go straight to the file descriptor, so a flood blocks this process at the pipe instead
// of queueing in memory, and the parent's output cap stops it.
const writeDirect = (fd: number) => (chunk: unknown): boolean => {
  writeLine(fd, typeof chunk === 'string' || chunk instanceof Uint8Array ? chunk : String(chunk))
  return true
}
process.stdout.write = writeDirect(1) as unknown as typeof process.stdout.write
process.stderr.write = writeDirect(2) as unknown as typeof process.stderr.write
console.log = noop
console.info = noop
console.warn = noop
console.error = noop
console.debug = noop
console.trace = noop
let importedFailed = false
let recordingLines = false
let firedLines: {line: number; callerLine: number | null}[] = []
console.assert = (condition?: unknown) => {
  const held = Boolean(condition)
  if (held) return
  if (!recordingLines) {
    importedFailed = true
    return
  }
  const frames = (new Error().stack ?? '').split('\n').slice(1).filter((frame) => !frame.includes(childPath))
  const lineIn = (frame: string | undefined) => {
    const at = frame == null ? -1 : frame.indexOf(`${job.source}:`)
    return frame == null || at < 0 ? null : Number.parseInt(frame.slice(at + job.source.length + 1), 10)
  }
  const line = lineIn(frames[0])
  if (line == null) {
    importedFailed = true
    return
  }
  let callerLine: number | null = null
  for (let index = 1; index < frames.length && callerLine == null; index++) callerLine = lineIn(frames[index])
  firedLines.push({line, callerLine})
}

/** Whether an imported module's console.assert failed since the last take, and resets the flag. */
function takeImportedFailure(): boolean {
  const failed = importedFailed
  importedFailed = false
  return failed
}

// The child reads its own RSS after a call, at most once per millisecond, and exits above the job's limit. So a call that
// retains memory, e.g. 64 MB per call, stops the child about one call past the limit instead of up to one ps poll interval
// past it. A call that never returns, or module initialization, is covered only by the parent's ps poller.
const RSS_CHECK_MS = 1
let lastRssCheck = 0
function checkRss() {
  const now = performance.now()
  if (now - lastRssCheck < RSS_CHECK_MS) return
  lastRssCheck = now
  const rssKb = Math.floor(process.memoryUsage.rss() / 1024)
  if (rssKb <= job.rssKb) return
  emit({type: 'rss', rssKb})
  process.exit(0)
}

const recorder = createRecorder(job.sites, job.stepBudget)
;(globalThis as Record<string, unknown>)['__fr'] = recorder

// A module whose top-level await never resolves would otherwise let the process exit; the parent's load step decides.
const keepAlive = setInterval(noop, 1000)
let instrumented: Record<string, unknown>
let source: Record<string, unknown> = {}
try {
  instrumented = (await import(job.instrumented)) as Record<string, unknown>
  if (job.mode === 'verify') source = (await import(job.source)) as Record<string, unknown>
} catch (error) {
  emit({type: 'load-failed', error: describeError(error)})
  process.exit(0)
}
clearInterval(keepAlive)
emit({type: 'loaded'})

/** A thrown value as text. Project code can throw a value String() can't convert, e.g. `Object.create(null)`. */
function describeError(error: unknown): string {
  try {
    return error instanceof Error ? `${error.name}: ${error.message}` : `threw ${String(error)}`
  } catch {
    return 'a value that String() cannot convert'
  }
}

function hasSubnormal(value: Value): boolean {
  if (typeof value === 'number') return value !== 0 && Math.abs(value) < 2.2250738585072014e-308
  if (value == null || typeof value !== 'object') return false
  return (Array.isArray(value) ? value : Object.values(value)).some(hasSubnormal)
}

// child-calls.ts causeOf, unchanged.
function causeOf(args: Value[], margin: number): CauseClass {
  if (hasSubnormal(args)) return 'subnormal'
  if (margin > 0 && margin <= 1e-6) return 'drift'
  if (maxMagnitude(args) > 1e4) return 'large'
  return 'ordinary'
}

// E/lib/runtime.ts allFinite: every number reachable through arrays and plain objects is finite, within 10,000 values.
function allFinite(value: unknown): boolean {
  const stack: unknown[] = [value]
  for (let visited = 0; stack.length > 0; visited++) {
    if (visited >= 10_000) return false
    const current = stack.pop()
    if (typeof current === 'number') {
      if (!Number.isFinite(current)) return false
    } else if (Array.isArray(current)) {
      for (const element of current) stack.push(element)
    } else if (current != null && typeof current === 'object') {
      for (const element of Object.values(current)) stack.push(element)
    }
  }
  return true
}

type EntryFunction = (...args: Value[]) => unknown
type CallOutcome = {kind: 'returned'} | {kind: 'discarded'} | {kind: 'over budget'} | {kind: 'threw'; error: string}

function entryFunction(module: Record<string, unknown>, entry: SweepEntry): EntryFunction {
  const fn = module[entry.name]
  if (typeof fn !== 'function') throw new Error(`the copy exports no function ${entry.name}`)
  return fn as EntryFunction
}

function call(fn: EntryFunction, args: Value[]): CallOutcome {
  try {
    fn(...args)
    return {kind: 'returned'}
  } catch (error) {
    if (error === DISCARD) return {kind: 'discarded'}
    if (error === BUDGET) return {kind: 'over budget'}
    return {kind: 'threw', error: describeError(error)}
  } finally {
    checkRss()
  }
}

function discardCauses(entry: SweepEntry): Int8Array {
  const causes = new Int8Array(job.sites.length).fill(-1)
  for (const discard of entry.discardSites) causes[discard.site] = DISCARD_CAUSES.indexOf(discard.cause)
  return causes
}

/** The cause of a discarded call: the discard site that failed, in site order. */
function failedDiscard(causes: Int8Array): DiscardCause {
  for (let touchedIndex = 0; touchedIndex < recorder.touchedCount; touchedIndex++) {
    const site = recorder.touched[touchedIndex]!
    if (causes[site]! >= 0 && recorder.levels[site]! >= 2) return DISCARD_CAUSES[causes[site]!]!
  }
  throw new Error('a call was discarded with no failing discard site')
}

function runEntry(entry: SweepEntry) {
  const fn = entryFunction(instrumented, entry)
  const lattice = compileLattice(entry, job.settings)
  const causes = discardCauses(entry)
  recorder.setEntry(entry.discardSites.map((discard) => discard.site))
  const siteCount = job.sites.length
  const touched = new Uint32Array(siteCount)
  const reached = new Uint32Array(siteCount)
  const level2 = new Uint32Array(siteCount)
  const level3 = new Uint32Array(siteCount)
  const byCause = new Uint32Array(siteCount * CAUSES.length)
  const first2 = new Array<FirstInput | null>(siteCount).fill(null)
  const first3 = new Array<FirstInput | null>(siteCount).fill(null)
  const firstReach = new Array<FirstInput | null>(siteCount).fill(null)
  const discards: Record<DiscardCause | 'R1', number> = {leading: 0, F1: 0, F3: 0, R1: 0}
  let inDomain = 0
  let overBudget = 0
  let threw = 0
  let firstThrow: string | null = null
  // The arguments of the current input as generated, regenerated by index only when a site needs them: a call may mutate
  // the arguments it was given.
  let regenerated: {index: number; args: Value[]; digest: number; encoded: string} | null = null
  const generated = (index: number) => {
    if (regenerated?.index !== index) {
      const args = inputAt(lattice, index).args
      regenerated = {index, args, digest: digestValue(DIGEST_START, args), encoded: encodeJson(args)}
    }
    return regenerated
  }
  const firstInput = (index: number, margin: number): FirstInput => {
    const input = generated(index)
    return {index, digest: input.digest, margin: Number.isNaN(margin) ? null : margin, cause: causeOf(input.args, margin), args: input.encoded}
  }
  const budget = job.settings.budget
  for (let index = 0; index < budget; index++) {
    if (index % job.heartbeatEvery === 0) emit({type: 'heartbeat'})
    const input = inputAt(lattice, index)
    resetRecorder(recorder)
    takeImportedFailure()
    const outcome = call(fn, input.args)
    const importedAssertFailed = takeImportedFailure()
    for (let touchedIndex = 0; touchedIndex < recorder.touchedCount; touchedIndex++) touched[recorder.touched[touchedIndex]!]! += 1
    switch (outcome.kind) {
      case 'discarded':
        discards[failedDiscard(causes)] += 1
        continue
      case 'over budget':
        overBudget += 1
        continue
      case 'threw':
        if (importedAssertFailed) break
        threw += 1
        firstThrow ??= outcome.error
        continue
      case 'returned':
        break
    }
    if (importedAssertFailed) {
      discards.R1 += 1
      continue
    }
    inDomain += 1
    for (let touchedIndex = 0; touchedIndex < recorder.touchedCount; touchedIndex++) {
      const site = recorder.touched[touchedIndex]!
      if (causes[site]! >= 0) continue
      reached[site]! += 1
      firstReach[site] ??= firstInput(index, NaN)
      const level = recorder.levels[site]!
      if (level < 2) continue
      level2[site]! += 1
      first2[site] ??= firstInput(index, recorder.margins[site]!)
      if (level < 3) continue
      level3[site]! += 1
      first3[site] ??= firstInput(index, recorder.margins[site]!)
      byCause[site * CAUSES.length + CAUSES.indexOf(causeOf(generated(index).args, recorder.margins[site]!))]! += 1
    }
  }
  const sites: SiteCounts[] = []
  for (let site = 0; site < siteCount; site++) {
    if (touched[site] === 0) continue
    const causeCounts: Record<CauseClass, number> = {subnormal: 0, drift: 0, large: 0, ordinary: 0}
    CAUSES.forEach((cause, causeIndex) => {
      causeCounts[cause] = byCause[site * CAUSES.length + causeIndex]!
    })
    sites.push({site, touched: touched[site]!, reached: reached[site]!, level2: level2[site]!, level3: level3[site]!, byCause: causeCounts, first2: first2[site] ?? null, first3: first3[site] ?? null, firstReach: firstReach[site] ?? null})
  }
  emit({type: 'entry', entry: entry.ordinal, drawn: budget, inDomain, discards, overBudget, threw, firstThrow, sites})
}

function runVerify() {
  const lattices = new Map<number, Lattice>()
  for (const item of job.items) {
    emit({type: 'heartbeat'})
    const entry = job.entries.find((candidate) => candidate.ordinal === item.entry)
    if (entry == null) throw new Error(`verification item ${item.item} names no entry of the job`)
    const lattice = lattices.get(entry.ordinal) ?? compileLattice(entry, job.settings)
    lattices.set(entry.ordinal, lattice)
    const causes = discardCauses(entry)
    const input = inputAt(lattice, item.index)
    const args = input.args
    recorder.setEntry(entry.discardSites.map((discard) => discard.site))
    resetRecorder(recorder)
    takeImportedFailure()
    recordingLines = false
    const instrumentedOutcome = call(entryFunction(instrumented, entry), structuredClone(args))
    const importedDuringInstrumented = takeImportedFailure()
    const level = recorder.levels[item.site]!
    const discarded = instrumentedOutcome.kind === 'discarded' ? failedDiscard(causes) : null
    firedLines = []
    recordingLines = true
    const sourceOutcome = call(entryFunction(source, entry), structuredClone(args))
    recordingLines = false
    const importedDuringSource = takeImportedFailure()
    const threw = instrumentedOutcome.kind === 'threw' ? instrumentedOutcome.error : sourceOutcome.kind === 'threw' ? sourceOutcome.error : null
    emit({
      type: 'verified', item: item.item, digestMatches: digestValue(DIGEST_START, args) === item.digest, discarded, overBudget: instrumentedOutcome.kind === 'over budget',
      threw, level, importedFailed: importedDuringInstrumented || importedDuringSource, finite: allFinite(args), fired: firedLines,
    })
  }
}

try {
  switch (job.mode) {
    case 'run':
      for (const entry of job.entries) runEntry(entry)
      break
    case 'verify':
      runVerify()
      break
  }
  emit({type: 'done', maxRssKb: process.resourceUsage().maxRSS})
} catch (error) {
  writeLine(1, `${stringify({type: 'crashed', error: describeError(error)})}\n`)
  process.exit(1)
}
process.exit(0)
