export {
  isDefinitelyEmptyArray,
  mergeArraySummary,
} from './array-summary.ts'
export {mergeAssumptions} from './assumptions.ts'
export {
  addNumbers,
  binaryExpr,
  callExpr,
  conditionalRunningSumNumber,
  divideNumbers,
  finiteNumberSet,
  finiteNumberValue,
  linearNameForExpression,
  maxNumberCases,
  mergeProvenance,
  moduloNumbers,
  multiplyNumbers,
  numberBranches,
  numberValue,
  plainNumber,
  powerNumbers,
  runningExtremumNumber,
  runningSumNumber,
  subtractNumbers,
  unknownNumber,
  withNumberCases,
} from './number-domain.ts'
export {
  finiteLiteralSetValues,
  joinValues,
  literalKey,
  literalValue,
  mergeElementValue,
  mergeNullishKind,
  nullableValue,
  nullValue,
  tupleArray,
  tupleElements,
  unknown,
  unknownArray,
  unknownArrayLength,
  unknownObject,
  valueWithAssumptions,
  valueWithDefaultedUndefined,
} from './value-domain.ts'
export type {
  ArrayLayout,
  ArrayOrigin,
  ArraySummary,
  ArrayValue,
  FactSource,
  LinearConstraint,
  LiteralPrimitive,
  LiteralValue,
  NullableValue,
  NullishKind,
  NullValue,
  NumberCase,
  NumberValue,
  ObjectValue,
  SequenceExpression,
  SequenceRelation,
  SequenceTerm,
  UnknownValue,
  Value,
} from './domain-types.ts'
